import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
import joblib

testing = pd.read_csv("./Testing.csv")
training = pd.read_csv("./Training.csv")

X_train = training.iloc[:, 0:132]
y_train = training.iloc[:, 132]

X_test = testing.iloc[:, 0:132]
y_test = testing.iloc[:, 132]

X = pd.concat([X_train, X_test])
y = pd.concat([y_train, y_test])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
rfc = RandomForestClassifier(random_state=10)
rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)
skf = StratifiedKFold(n_splits=5)
scores = cross_val_score(rfc, X_train, y_train, cv=skf)
print(scores)
print(classification_report(y_test, y_pred))

features = pd.DataFrame(rfc.feature_importances_, index=X_train.columns)

features.to_csv("features.csv")

diabetes = pd.DataFrame({
    'itching': [0],
    'skin_rash': [0],
    'nodal_skin_eruptions': [0],
    'continuous_sneezing': [0],
    'shivering': [0],
    'chills': [0],
    'joint_pain': [0],
    'stomach_pain': [0],
    'acidity': [0],
    'ulcers_on_tongue': [0],
    'muscle_wasting': [0],
    'vomiting': [0],
    'burning_micturition': [0],
    'spotting_ urination': [0],
    'fatigue': [1],
    'weight_gain': [0],
    'anxiety': [0],
    'cold_hands_and_feets': [0],
    'mood_swings': [0],
    'weight_loss': [1],
    'restlessness': [0],
    'lethargy': [1],
    'patches_in_throat': [0],
    'irregular_sugar_level': [1],
    'cough': [0],
    'high_fever': [0],
    'sunken_eyes': [0],
    'breathlessness': [0],
    'sweating': [1],
    'dehydration': [1],
    'indigestion': [0],
    'headache': [0],
    'yellowish_skin': [0],
    'dark_urine': [0],
    'nausea': [0],
    'loss_of_appetite': [0],
    'pain_behind_the_eyes': [0],
    'back_pain': [0],
    'constipation': [0],
    'abdominal_pain': [0],
    'diarrhoea': [0],
    'mild_fever': [0],
    'yellow_urine': [0],
    'yellowing_of_eyes': [0],
    'acute_liver_failure': [0],
    'fluid_overload': [0],
    'swelling_of_stomach': [0],
    'swelled_lymph_nodes': [0],
    'malaise': [1],
    'blurred_and_distorted_vision': [1],
    'phlegm': [0],
    'throat_irritation': [0],
    'redness_of_eyes': [0],
    'sinus_pressure': [0],
    'runny_nose': [0],
    'congestion': [0],
    'chest_pain': [0],
    'weakness_in_limbs': [1],
    'fast_heart_rate': [0],
    'pain_during_bowel_movements': [0],
    'pain_in_anal_region': [0],
    'bloody_stool': [0],
    'irritation_in_anus': [0],
    'neck_pain': [0],
    'dizziness': [1],
    'cramps': [0],
    'bruising': [0],
    'obesity': [1],
    'swollen_legs': [0],
    'swollen_blood_vessels': [0],
    'puffy_face_and_eyes': [0],
    'enlarged_thyroid': [0],
    'brittle_nails': [0],
    'swollen_extremeties': [0],
    'excessive_hunger': [1],
    'extra_marital_contacts': [0],
    'drying_and_tingling_lips': [0],
    'slurred_speech': [0],
    'knee_pain': [0],
    'hip_joint_pain': [0],
    'muscle_weakness': [1],
    'stiff_neck': [0],
    'swelling_joints': [0],
    'movement_stiffness': [0],
    'spinning_movements': [0],
    'loss_of_balance': [0],
    'unsteadiness': [0],
    'weakness_of_one_body_side': [0],
    'loss_of_smell': [0],
    'bladder_discomfort': [0],
    'foul_smell_of urine': [0],
    'continuous_feel_of_urine': [0],
    'passage_of_gases': [0],
    'internal_itching': [0],
    'toxic_look_(typhos)': [0],
    'depression': [1],
    'irritability': [1],
    'muscle_pain': [0],
    'altered_sensorium': [0],
    'red_spots_over_body': [0],
    'belly_pain': [0],
    'abnormal_menstruation': [0],
    'dischromic _patches': [0],
    'watering_from_eyes': [0],
    'increased_appetite': [1],
    'polyuria': [1],
    'family_history': [1],
    'mucoid_sputum': [0],
    'rusty_sputum': [0],
    'lack_of_concentration': [1],
    'visual_disturbances': [1],
    'receiving_blood_transfusion': [0],
    'receiving_unsterile_injections': [0],
    'coma': [0],
    'stomach_bleeding': [0],
    'distention_of_abdomen': [0],
    'history_of_alcohol_consumption': [0],
    'fluid_overload.1': [0],
    'blood_in_sputum': [0],
    'prominent_veins_on_calf': [0],
    'palpitations': [0],
    'painful_walking': [0],
    'pus_filled_pimples': [0],
    'blackheads': [0],
    'scurring': [0],
    'skin_peeling': [0],
    'silver_like_dusting': [0],
    'small_dents_in_nails': [0],
    'inflammatory_nails': [0],
    'blister': [0],
    'red_sore_around_nose': [0],
    'yellow_crust_ooze': [0]
})

malaria = pd.DataFrame({
    'itching': [0],
    'skin_rash': [0],
    'nodal_skin_eruptions': [0],
    'continuous_sneezing': [0],
    'shivering': [1],
    'chills': [1],
    'joint_pain': [1],
    'stomach_pain': [0],
    'acidity': [0],
    'ulcers_on_tongue': [0],
    'muscle_wasting': [0],
    'vomiting': [0],
    'burning_micturition': [0],
    'spotting_ urination': [0],
    'fatigue': [1],
    'weight_gain': [0],
    'anxiety': [0],
    'cold_hands_and_feets': [0],
    'mood_swings': [0],
    'weight_loss': [0],
    'restlessness': [1],
    'lethargy': [1],
    'patches_in_throat': [0],
    'irregular_sugar_level': [0],
    'cough': [0],
    'high_fever': [1],
    'sunken_eyes': [0],
    'breathlessness': [0],
    'sweating': [1],
    'dehydration': [1],
    'indigestion': [0],
    'headache': [1],
    'yellowish_skin': [1],
    'dark_urine': [0],
    'nausea': [0],
    'loss_of_appetite': [1],
    'pain_behind_the_eyes': [0],
    'back_pain': [0],
    'constipation': [0],
    'abdominal_pain': [1],
    'diarrhoea': [0],
    'mild_fever': [0],
    'yellow_urine': [0],
    'yellowing_of_eyes': [1],
    'acute_liver_failure': [0],
    'fluid_overload': [0],
    'swelling_of_stomach': [0],
    'swelled_lymph_nodes': [0],
    'malaise': [1],
    'blurred_and_distorted_vision': [0],
    'phlegm': [0],
    'throat_irritation': [0],
    'redness_of_eyes': [0],
    'sinus_pressure': [0],
    'runny_nose': [0],
    'congestion': [0],
    'chest_pain': [0],
    'weakness_in_limbs': [1],
    'fast_heart_rate': [0],
    'pain_during_bowel_movements': [0],
    'pain_in_anal_region': [0],
    'bloody_stool': [0],
    'irritation_in_anus': [0],
    'neck_pain': [0],
    'dizziness': [0],
    'cramps': [0],
    'bruising': [0],
    'obesity': [0],
    'swollen_legs': [0],
    'swollen_blood_vessels': [0],
    'puffy_face_and_eyes': [0],
    'enlarged_thyroid': [0],
    'brittle_nails': [0],
    'swollen_extremeties': [0],
    'excessive_hunger': [0],
    'extra_marital_contacts': [0],
    'drying_and_tingling_lips': [0],
    'slurred_speech': [0],
    'knee_pain': [0],
    'hip_joint_pain': [0],
    'muscle_weakness': [1],
    'stiff_neck': [0],
    'swelling_joints': [0],
    'movement_stiffness': [0],
    'spinning_movements': [0],
    'loss_of_balance': [0],
    'unsteadiness': [0],
    'weakness_of_one_body_side': [0],
    'loss_of_smell': [0],
    'bladder_discomfort': [0],
    'foul_smell_of urine': [0],
    'continuous_feel_of_urine': [0],
    'passage_of_gases': [0],
    'internal_itching': [0],
    'toxic_look_(typhos)': [0],
    'depression': [0],
    'irritability': [0],
    'muscle_pain': [1],
    'altered_sensorium': [0],
    'red_spots_over_body': [0],
    'belly_pain': [1],
    'abnormal_menstruation': [0],
    'dischromic _patches': [0],
    'watering_from_eyes': [0],
    'increased_appetite': [0],
    'polyuria': [0],
    'family_history': [0],
    'mucoid_sputum': [0],
    'rusty_sputum': [0],
    'lack_of_concentration': [0],
    'visual_disturbances': [0],
    'receiving_blood_transfusion': [0],
    'receiving_unsterile_injections': [0],
    'coma': [0],
    'stomach_bleeding': [0],
    'distention_of_abdomen': [0],
    'history_of_alcohol_consumption': [0],
    'fluid_overload.1': [0],
    'blood_in_sputum': [0],
    'prominent_veins_on_calf': [0],
    'palpitations': [0],
    'painful_walking': [0],
    'pus_filled_pimples': [0],
    'blackheads': [0],
    'scurring': [0],
    'skin_peeling': [0],
    'silver_like_dusting': [0],
    'small_dents_in_nails': [0],
    'inflammatory_nails': [0],
    'blister': [0],
    'red_sore_around_nose': [0],
    'yellow_crust_ooze': [0]
})

typhoid = pd.DataFrame({
    'itching': [0],
    'skin_rash': [0],
    'nodal_skin_eruptions': [0],
    'continuous_sneezing': [0],
    'shivering': [0],
    'chills': [1],
    'joint_pain': [1],
    'stomach_pain': [1],
    'acidity': [0],
    'ulcers_on_tongue': [0],
    'muscle_wasting': [0],
    'vomiting': [1],
    'burning_micturition': [0],
    'spotting_ urination': [0],
    'fatigue': [1],
    'weight_gain': [0],
    'anxiety': [0],
    'cold_hands_and_feets': [0],
    'mood_swings': [0],
    'weight_loss': [1],
    'restlessness': [1],
    'lethargy': [1],
    'patches_in_throat': [0],
    'irregular_sugar_level': [0],
    'cough': [0],
    'high_fever': [1],
    'sunken_eyes': [0],
    'breathlessness': [0],
    'sweating': [1],
    'dehydration': [1],
    'indigestion': [0],
    'headache': [1],
    'yellowish_skin': [1],
    'dark_urine': [0],
    'nausea': [1],
    'loss_of_appetite': [1],
    'pain_behind_the_eyes': [0],
    'back_pain': [0],
    'constipation': [1],
    'abdominal_pain': [1],
    'diarrhoea': [0],
    'mild_fever': [0],
    'yellow_urine': [0],
    'yellowing_of_eyes': [0],
    'acute_liver_failure': [0],
    'fluid_overload': [0],
    'swelling_of_stomach': [0],
    'swelled_lymph_nodes': [0],
    'malaise': [1],
    'blurred_and_distorted_vision': [0],
    'phlegm': [0],
    'throat_irritation': [0],
    'redness_of_eyes': [0],
    'sinus_pressure': [0],
    'runny_nose': [0],
    'congestion': [0],
    'chest_pain': [0],
    'weakness_in_limbs': [1],
    'fast_heart_rate': [0],
    'pain_during_bowel_movements': [0],
    'pain_in_anal_region': [0],
    'bloody_stool': [0],
    'irritation_in_anus': [0],
    'neck_pain': [0],
    'dizziness': [0],
    'cramps': [0],
    'bruising': [0],
    'obesity': [0],
    'swollen_legs': [0],
    'swollen_blood_vessels': [0],
    'puffy_face_and_eyes': [0],
    'enlarged_thyroid': [0],
    'brittle_nails': [0],
    'swollen_extremeties': [0],
    'excessive_hunger': [0],
    'extra_marital_contacts': [0],
    'drying_and_tingling_lips': [0],
    'slurred_speech': [0],
    'knee_pain': [0],
    'hip_joint_pain': [0],
    'muscle_weakness': [0],
    'stiff_neck': [0],
    'swelling_joints': [0],
    'movement_stiffness': [0],
    'spinning_movements': [0],
    'loss_of_balance': [0],
    'unsteadiness': [0],
    'weakness_of_one_body_side': [0],
    'loss_of_smell': [0],
    'bladder_discomfort': [0],
    'foul_smell_of urine': [0],
    'continuous_feel_of_urine': [0],
    'passage_of_gases': [0],
    'internal_itching': [0],
    'toxic_look_(typhos)': [1],
    'depression': [0],
    'irritability': [1],
    'muscle_pain': [1],
    'altered_sensorium': [0],
    'red_spots_over_body': [1],
    'belly_pain': [1],
    'abnormal_menstruation': [0],
    'dischromic _patches': [0],
    'watering_from_eyes': [0],
    'increased_appetite': [0],
    'polyuria': [0],
    'family_history': [0],
    'mucoid_sputum': [0],
    'rusty_sputum': [0],
    'lack_of_concentration': [0],
    'visual_disturbances': [0],
    'receiving_blood_transfusion': [0],
    'receiving_unsterile_injections': [0],
    'coma': [0],
    'stomach_bleeding': [0],
    'distention_of_abdomen': [1],
    'history_of_alcohol_consumption': [0],
    'fluid_overload.1': [0],
    'blood_in_sputum': [0],
    'prominent_veins_on_calf': [0],
    'palpitations': [0],
    'painful_walking': [0],
    'pus_filled_pimples': [0],
    'blackheads': [0],
    'scurring': [0],
    'skin_peeling': [0],
    'silver_like_dusting': [0],
    'small_dents_in_nails': [0],
    'inflammatory_nails': [0],
    'blister': [0],
    'red_sore_around_nose': [0],
    'yellow_crust_ooze': [0]
})

diabetes_prediction = rfc.predict(diabetes)
print("Predicted disease:", diabetes_prediction[0])

malaria_prediction = rfc.predict(malaria)
print("Predicted disease:", malaria_prediction[0])

typhoid_prediction = rfc.predict(typhoid)
print("Predicted disease:", typhoid_prediction[0])

joblib.dump(rfc, filename="randomForestModel.joblib")